const ROLES = {
  ADMIN: 'ADMIN',
  JOB_ADVISOR: 'JOB_ADVISOR',
  MECHANICAL: 'MECHANICAL',
  ELECTRICAL: 'ELECTRICAL',
  BODY_REPAIR: 'BODY_REPAIR',
  PAINT: 'PAINT',
  GENERAL_INSPECTION: 'GENERAL_INSPECTION',
  CUSTOMER: 'CUSTOMER',
};

const DEPARTMENTS = {
  MECHANICAL: 'MECHANICAL',
  ELECTRICAL: 'ELECTRICAL',
  BODY_REPAIR: 'BODY_REPAIR',
  PAINT: 'PAINT',
  GENERAL_INSPECTION: 'GENERAL_INSPECTION',
};

const JOB_STATUS = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const ROLE_TO_DEPARTMENT = {
  [ROLES.MECHANICAL]: DEPARTMENTS.MECHANICAL,
  [ROLES.ELECTRICAL]: DEPARTMENTS.ELECTRICAL,
  [ROLES.BODY_REPAIR]: DEPARTMENTS.BODY_REPAIR,
  [ROLES.PAINT]: DEPARTMENTS.PAINT,
  [ROLES.GENERAL_INSPECTION]: DEPARTMENTS.GENERAL_INSPECTION,
};

const DEPARTMENT_ROLES = [
  ROLES.MECHANICAL,
  ROLES.ELECTRICAL,
  ROLES.BODY_REPAIR,
  ROLES.PAINT,
  ROLES.GENERAL_INSPECTION,
];

const ALL_JOBS_ROLES = [ROLES.ADMIN, ROLES.JOB_ADVISOR];

module.exports = {
  ROLES,
  DEPARTMENTS,
  JOB_STATUS,
  ROLE_TO_DEPARTMENT,
  ALL_JOBS_ROLES,
  DEPARTMENT_ROLES,
};
