const ROLES = {
  ADMIN: 'ADMIN',
  JOB_ADVISOR: 'JOB_ADVISOR',
  MECHANICAL: 'MECHANICAL',
  ELECTRICAL: 'ELECTRICAL',
  BODY_REPAIR: 'BODY_REPAIR',
  PAINT: 'PAINT',
  GENERAL_INSPECTION: 'GENERAL_INSPECTION',
  CUSTOMER: 'CUSTOMER',
};

const DEPARTMENTS = {
  MECHANICAL: 'MECHANICAL',
  ELECTRICAL: 'ELECTRICAL',
  BODY_REPAIR: 'BODY_REPAIR',
  PAINT: 'PAINT',
  GENERAL_INSPECTION: 'GENERAL_INSPECTION',
};

const JOB_STATUS = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const PENDING_JOB_STATUSES = [
  JOB_STATUS.PENDING,
  JOB_STATUS.ASSIGNED,
  JOB_STATUS.IN_PROGRESS,
  JOB_STATUS.PAUSED,
];

const PAUSE_REASONS = {
  TEA_BREAK: 'TEA_BREAK',
  LUNCH_BREAK: 'LUNCH_BREAK',
  PART_PENDING: 'PART_PENDING',
};

const PAUSE_REASON_LABELS = {
  TEA_BREAK: 'Tea Break',
  LUNCH_BREAK: 'Lunch Break',
  PART_PENDING: 'Part Pending',
};

const ROLE_TO_DEPARTMENT = {
  [ROLES.MECHANICAL]: DEPARTMENTS.MECHANICAL,
  [ROLES.ELECTRICAL]: DEPARTMENTS.ELECTRICAL,
  [ROLES.BODY_REPAIR]: DEPARTMENTS.BODY_REPAIR,
  [ROLES.PAINT]: DEPARTMENTS.PAINT,
  [ROLES.GENERAL_INSPECTION]: DEPARTMENTS.GENERAL_INSPECTION,
};

const DEPARTMENT_ROLES = [
  ROLES.MECHANICAL,
  ROLES.ELECTRICAL,
  ROLES.BODY_REPAIR,
  ROLES.PAINT,
  ROLES.GENERAL_INSPECTION,
];

const ALL_JOBS_ROLES = [ROLES.ADMIN, ROLES.JOB_ADVISOR];

module.exports = {
  ROLES,
  DEPARTMENTS,
  JOB_STATUS,
  PENDING_JOB_STATUSES,
  PAUSE_REASONS,
  PAUSE_REASON_LABELS,
  ROLE_TO_DEPARTMENT,
  ALL_JOBS_ROLES,
  DEPARTMENT_ROLES,
};
